# Generated by Django 4.0.6 on 2022-07-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TherapyReady', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='image',
            field=models.TextField(default=''),
        ),
    ]
